version: "3.9"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: cine
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  app:
    build: ./backend
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: cine
      DB_USER: postgres
      DB_PASSWORD: admin
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: supersecretkeymustbeatleast32byteslong1234
      WOMPI_PUBLIC_KEY: pub_test_YourPublicKey
      WOMPI_INTEGRITY_KEY: integrity_test_YourIntegrityKey
      WOMPI_EVENTS_SECRET: events_test_YourEventsSecret
      WOMPI_REDIRECT_URL: http://localhost:8080/checkout/return
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis

  # Desarrollo con hot reload (DevTools)
  app-dev:
    image: maven:3.9.6-eclipse-temurin-17
    working_dir: /app
    command: mvn -Dspring-boot.run.profiles=dev spring-boot:run
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: cine
      DB_USER: postgres
      DB_PASSWORD: admin
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: change-me-super-secret
      WOMPI_PUBLIC_KEY: pub_test_YourPublicKey
      WOMPI_INTEGRITY_KEY: integrity_test_YourIntegrityKey
      WOMPI_EVENTS_SECRET: events_test_YourEventsSecret
      WOMPI_REDIRECT_URL: http://localhost:8080/checkout/return
    volumes:
      - ./backend:/app
      - m2:/root/.m2
    depends_on:
      - postgres
      - redis

volumes:
  pgdata:
  m2:
