spring:
  thymeleaf:
    cache: false
  devtools:
    livereload:
      enabled: true
  jpa:
    properties:
      hibernate:
        show_sql: true
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework.web: INFO

